import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import Navbar from "./Navbar";
import AuthProvider from "./api/auth/[...nextauth]/Provider";

const font = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AuthProvider>
            <Navbar>{children}</Navbar>
        </AuthProvider>
      </body>
    </html>
  );
}
